### PR TITLE
please consider these revisions :)

### PR DESCRIPTION
**Pull request by paulo-innplaylabs**
Hi there!

I am "nukesheart" from Romhacking.net - I just want to share you this revision I made for the weapons/armors/enemies and stuff.

For the enemies:

I tweaked mostly all their resistances - now not almost every enemy is weak to HIT and HOLY and FIRE.

In a nutshell this is what I followed (with some exceptions):

Skeletons: weak to holy/fire, strong to cut
Armored: weak to lightning/water, strong to cut
Living Creatures: weak to status effects, strong to hit
Aquatic: weak to cut/lightning, strong to water/ice/fire
Spirits: weak to dark, strong to holy

..and some other tweaks. This way some weapons still have some viability while roaming the castle against different enemies.

For the weapons, I considered giving higher values to weapons that are dropped or sold at the shop - to make it a bit "special". Example is the Icebrand - you can just get it lying around in the catacombs. So I made it a bit weaker than firebrand/thunderbrand where you need to spend $$ to get.

Some other tweaks for the weapons/equips you can just check and let me know if you liked it!

Maybe try to do a normal run with it as well? 

If possible to expose the item description in json I'm willing to walk a long mile to modify some equips so that the description also includes the new changes.

Thanks!

### CODE REVIEW

**Comment by Lakifume** [comment]
Alright so I did a quick update to fix the moon rod thing and when I have more time I'll see what I can do with your revisions. Though I will say that some of them are bit too much (I am not giving Alucard resistance to HIT in any shape or form).
As for the description thing I can't really structure those in a json as editing them is easy but very specific. If you want to manually change some of those yourself you can search their corresponding string and edit them directly in the rom with hex editor (they can't have more characters than the original string though). Do that BEFORE applying the mod though, not after.

**Comment by paulo-innplaylabs** [comment]
Hey lakifume!

I rebalanced a LOT in this one:
Alucard starts with a lot of HP
Enemies have lots of HP
You both deal high number damages
Equipments stats adjusted for this progression - even for INT (since it's the only basis for subweapon/magic damage)
Removed all immunity from circlets - just gave resistances 

First purpose of this balance is to prevent getting the STR > weaponATK to avoid the double damage later in the game
This also makes the progression of stats less steep - meaning the "challenge" is always there, but the difficulty slowly curves higher the further you are in the game.
Also elemental resistances for Alucard isn't OP this time, since you still get big number damage even if you resist some damages (instead of just getting 1 damage before)

(I'm still doing runs for this balancing so I might change something else...but if you want you can try it yourself and hope you like it! It's been great so far for me)

**Comment by paulo-innplaylabs** [comment]
Hi Lakufume! I finally finalized the final version of my rebalancing of the game using your hack :D

The difficulty curves from easy to moderate to very hard in the later part of the game and the players needed some full understanding of the game mechanics/spells/strenghts-weaknesses/secret items to survive some of the later bosses - but it's fair and possible :3

Yeah maybe try this one just for fun if you want to try another playthrough! Hope you like it.
Also I would like to share this to others as well, maybe I'll put another review in romhacking.net and tell that you can actually edit your own balancing, then share mine as link that they can download and put in the Data folder and play ✌️

**Comment by ametalslimedrawsnear** [comment]
Is there an option to have Death take your starting weapons?

**Comment by ametalslimedrawsnear** [comment]
It appears that the latest update does not work.  Monsters are taken out  with one hit and have no resistances.  I have patched clean versions of the game several times to test.

**Pull request closed without merging**
